---
#
# Install MongoDB database ensuring Huge Pages is disabled and numactrl is present
# 

- name: Configure a script to disable huge pages and install NUMA control (which will be run by the mongod startup script)
  copy: src=os/disable-transparent-hugepages.j2 dest=/etc/init.d/disable-transparent-hugepages mode=a+x
# Hack to reload systemd settings otherwise sometimes systemd won't find 'disable-transparent-hugepages',
#  see: https://github.com/ansible/ansible-modules-core/issues/4113
- systemd: daemon_reload=yes name=sshd
- service: name=disable-transparent-hugepages enabled=yes state=started
- yum: name=numactl state=latest

- name: Install and configure MongoDB from the enterprise binaries repository
  template: src=files/mongod/mongodb-enterprise.repo.j2 dest=/etc/yum.repos.d/mongodb-enterprise.repo
- copy: src=mongod/99-mongodb-nproc.conf.j2 dest=/etc/security/limits.d/99-mongodb-nproc.conf
- yum: name=mongodb-enterprise state=latest
- template: src=files/mongod/mongod.conf.j2 dest=/etc/mongod.conf owner=mongod group=mongod mode=u+rw


